name: flutter_ui_challenge
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 状态管理
  flutter_riverpod: ^1.0.4
  # 存储
  shared_preferences: ^2.0.15
  # 路由
  fluro: ^2.0.3
  # Toast
  oktoast: ^3.2.0
  # 图片选择
  image_picker: ^0.8.5+3
  # 图片缓存
  extended_image: ^6.2.1
  # 滚动到index
  scrollable_positioned_list: ^0.3.2
  equatable: ^2.0.3
  # webview
  webview_flutter: 3.0.4
  # 锁
  synchronized: ^3.0.0+2
  # 使用到了DateFormat
  intl: ^0.17.0
  # json转model相关
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  # 悬停 & 分区 & scrollToIndex
  flutter_table_list_view: ^0.0.1
  flutter_easy_segment: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
    - assets/lottie/

  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
